---
- stat:
    path: "{{ cloudflared_bin_location }}/cloudflared"
  register: cloudflared_binary

- set_fact:
    cloudflared_installed: "{{ cloudflared_binary.stat.exists | default(false) }}"

- name: install package
  import_tasks: install_package.yml
  when: (not cloudflared_installed) and (ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'apt') and (ansible_architecture == 'x86_64' or ansible_architecture == 'arm')

- name: install binary
  import_tasks: install_binary.yml
  when: (not cloudflared_installed) and (pkg_mgr_output is undefined or pkg_mgr_output is failed)

- name: Set network capabilities for cloudflared
  capabilities:
    path: "{{ cloudflared_bin_location }}/cloudflared"
    capability: cap_net_bind_service+ep
    state: present

- command: cloudflared update
  register: update_command
  changed_when: update_command.rc == '64'

- name: create application user
  user:
    name: cloudflared
    system: yes

- name: template config file
  template:
    src: cloudflared.j2
    dest: /etc/default/cloudflared
    owner: cloudflared
    group: cloudflared
  notify: restart cloudflared service

- name: copy systemd service
  copy:
    src: cloudflared.service
    dest: /lib/systemd/system/
    owner: root
    group: root
    mode: 0644
  notify: restart cloudflared service
  register: service

- name: enable systemd service
  service:
    name: cloudflared
    enabled: "{{ cloudflared_enable_service }}"
  when: service.changed

- name: Allow port in firewall
  ufw:
    rule: allow
    port: "{{ cloudflared_port }}"
    comment: "allow cloudflared"
  when: cloudflared_allow_firewall
